# Generated by Django 4.2.27 on 2026-02-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('ISSUE_ID', 'ID Issuance'), ('VERIFY_ID', 'ID Verification'), ('UPDATE_PROFILE', 'Profile Update')], max_length=50)),
                ('user_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
