# Generated by Django 4.2.27 on 2026-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('ISSUE_ID', 'ID Issuance'), ('VERIFY_ID', 'ID Verification'), ('UPDATE_PROFILE', 'Profile Update'), ('ADMIN_LOGIN', 'Admin Login')], max_length=50),
        ),
    ]
