# Generated by Django 4.2.27 on 2026-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0003_auditlog_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CITIZEN', 'Citizen'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('ISSUE_ID', 'ID Issuance'), ('VERIFY_ID', 'ID Verification'), ('UPDATE_PROFILE', 'Profile Update'), ('ADMIN_LOGIN', 'Admin Login'), ('CREATE_ADMIN', 'Create Admin'), ('DELETE_ADMIN', 'Delete Admin'), ('IMPORT_DOCS', 'Import Documents')], max_length=50),
        ),
    ]
