# Generated by Django 4.2.27 on 2026-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('GOVT_OFFICIAL', 'Government Official'), ('EMPLOYER_ADMIN', 'Employer - Admin (HR)'), ('EMPLOYER_VERIFIER', 'Employer - Verifier (Security)'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=20),
        ),
    ]
