# Generated by Django 4.2.27 on 2026-02-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('FIELD_WORKER', 'Field Worker (Data Collector)'), ('EMPLOYER_ADMIN', 'Employer - Admin (HR)'), ('EMPLOYER_VERIFIER', 'Employer - Verifier (Security)'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=20),
        ),
    ]
