# Generated by Django 4.2.27 on 2026-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DATA_COLLECTOR', 'Field Data Collector (NRB/CRS)'), ('INVESTIGATOR', 'Investigation Officer (DCI/EACC)'), ('DATA_CONTROLLER', 'Data Controller (CEO/PS)'), ('DPO', 'Data Protection Officer'), ('ORG_ADMIN', 'System Administrator (Org)'), ('HR_MANAGER', 'Human Resource Manager'), ('INT_AUDITOR', 'Internal Auditor'), ('VERIFIER', 'Verifier / Enrollment Officer'), ('CITIZEN', 'Citizen'), ('SYSTEM_ADMIN', 'System Admin (Platform)')], default='CITIZEN', max_length=20),
        ),
    ]
