# Generated by Django 4.2.27 on 2026-02-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.CharField(max_length=20, unique=True)),
                ('issuance_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('public_key', models.TextField()),
                ('doc_type', models.CharField(default='org.iso.18013.5.1.mDL', max_length=50)),
            ],
        ),
    ]
