# Generated by Django 4.2.27 on 2026-02-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_id', '0002_issuancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalid',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License')], default='NATIONAL_ID', max_length=20),
        ),
        migrations.AddField(
            model_name='digitalid',
            name='national_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='digitalid',
            name='citizen_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='digitalid',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10),
        ),
    ]
