# Generated by Django 5.2.8 on 2026-02-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceBiometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_biometrics', to='citizens.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='FingerprintBiometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_type', models.CharField(choices=[('L_THUMB', 'Left Thumb'), ('L_INDEX', 'Left Index'), ('R_THUMB', 'Right Thumb'), ('R_INDEX', 'Right Index')], max_length=20)),
                ('template_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='citizens.citizen')),
            ],
        ),
    ]
